query getVaultsV2BasicData($address: String!, $chainId: Int!) {
  vaultV2ByAddress(address: $address, chainId: $chainId) {
    adapters {
      items {
        address
        type
      }
    }
    totalAssets
    idleAssets
    caps {
      items {
        type
        id
        idData
        absoluteCap
        relativeCap
      }
    }
  }
}
