name: Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test-strategies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Build config
        run: pnpm build:config
      - name: Install Foundry (anvil, forge, cast)
        uses: foundry-rs/foundry-toolchain@8789b3e21e6c11b2697f5eb56eddae542f746c10 # v1
        with:
          version: stable
      - name: Run strategies tests
        run: pnpm test:strategies
        env:
          RPC_URL_1: ${{ secrets.RPC_URL_1 }}

  test-execution:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4
      - name: Set up pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      - name: Set up Node.js
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4
        with:
          node-version-file: .nvmrc
          cache: pnpm
      - name: Install dependencies
        run: pnpm i --frozen-lockfile
      - name: Build config
        run: pnpm build:config
      - name: Install Foundry (anvil, forge, cast)
        uses: foundry-rs/foundry-toolchain@8789b3e21e6c11b2697f5eb56eddae542f746c10 # v1
        with:
          version: stable
      - name: Run execution tests
        run: pnpm test:execution
        env:
          RPC_URL_1: ${{ secrets.RPC_URL_1 }}
